on:
  push: #pull_request:
    branches: 
      - main
      - workflow

name: "Build & Release Android App"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: '17'
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: '3.24.3'
          channel: 'stable'
      - run: flutter pub get
      - run: flutter build apk --split-per-abi
      - name: Push to Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "build/app/outputs/apk/release/*"
          tag: v1.0.${{ github.run_number }}
          token: ${{ secrets.TOKEN}}